### PR TITLE
Use Sprocket GitHub Action in CI

### PR DESCRIPTION
**Pull request by adthrasher**
Update the Sprocket lint in the workflow to use the public Sprocket GitHub Action. 

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Make sure your code validates (`womtool validate` or `miniwdl check`).
- [ ] Ensure the test suite passes.
- [ ] Documentation is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `.dockstore.yml` is updated.
- [ ] `README.md` is updated.

### CODE REVIEW

**Comment by claymcleod** [comment]
I wonder if we should also update the PR checklist to include the code passing the sprocket lints?

**Comment by adthrasher** [comment]
@vsmalladi - I can't request a review from you, so tagging to make sure this isn't missed. We've published a GitHub Action to wrap Sprocket's `check` and `lint` functionality.

**Review by vsmalladi — APPROVED** [review]
LGTM

**Comment by vsmalladi** [comment]
Merge when ready.

**Comment by adthrasher** [comment]
@vsmalladi - I don't have permission to merge.

**Pull request merged**
